#ifndef LISTAS_DUPLAMENTE_ENCADEADAS_INDEX_H
#define LISTAS_DUPLAMENTE_ENCADEADAS_INDEX_H

// Declarações de todas as questões de Listas Duplamente Encadeadas

void executarQuestaoListasDuplamenteEncadeadas1(void);
void executarQuestaoListasDuplamenteEncadeadas1Predefinido(void);
void executarQuestaoListasDuplamenteEncadeadas1EntradaManual(void);

void executarQuestaoListasDuplamenteEncadeadas2(void);
void executarQuestaoListasDuplamenteEncadeadas2Predefinido(void);
void executarQuestaoListasDuplamenteEncadeadas2EntradaManual(void);

void executarQuestaoListasDuplamenteEncadeadas3(void);
void executarQuestaoListasDuplamenteEncadeadas3Predefinido(void);
void executarQuestaoListasDuplamenteEncadeadas3EntradaManual(void);

void executarQuestaoListasDuplamenteEncadeadas4(void);
void executarQuestaoListasDuplamenteEncadeadas4Predefinido(void);
void executarQuestaoListasDuplamenteEncadeadas4EntradaManual(void);

void executarQuestaoListasDuplamenteEncadeadas5(void);
void executarQuestaoListasDuplamenteEncadeadas5Predefinido(void);
void executarQuestaoListasDuplamenteEncadeadas5EntradaManual(void);

#endif
